version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: procurement_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hotanhotan1.
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/procurement_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hotanhotan1.
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend